### ISSUE TITLE
User cut generation problem in Cut Callback(s)

### ISSUE THREAD

**Issue by arinik9** [ZacharieALES/k-partitioning-cplex#1]
Hi @ZacharieALES 

Thank you very much for having made this repository public!

If I am not wrong, I found a bug in the code. I was asking myself why the program could not generate user cuts during Branch&Bound step. You use probably all of the files in the *cut_callback* package, but I needed actually only *FastCutCallback.java* and *CutCallback_all.java*. The bug is similar in those java files: We need to iterate over '*sep*' variable (defined in *AbstractCutCallback.java*) instead of '*sep_algo*' which is empty in the *separates()* method.

I hope this is correct and improves the code a little bit better.
Nejat

**Comment by ZacharieALES** [comment]
Hello,

Thank you for pointing that out. I think the best is to remove the sep_algo variables. 
The code has been changed.
